export interface IvPaciente
{    
    uid_paciente?: number;
    ci?: string;
    nombre?: string;
    apellido?: string;
    id_departamento?: number;
    es_contratista?: boolean;
    fechanac?: string;
    sexo?: string;
    cargo?: string;
    turno?: string;
    antiguedad_puesto?: string;
    fecha_ingreso?: string;
    tipo_sangre?: string;
    lugar_nac ?: string;
    edo_civil ?: string;
    nacionalidad?: string;
    telefono?: string;
    direccion_hab?: string;
    fecharegistro?: string;
    id_contratista?: number;
    mano_dominante?: string;
    frecuencia_rotacion?: string;
    nivel_educativo?: string;
    tipo_vivienda?: string;
    vivienda_propia?: string;
    medio_transp_trabajo?: string;
    alergia?: string;
    tipo_discapacidad?: string;
    desc_discapacidad?: string;
    estado_paciente?: string;
    edad?: any;
    nombre_completo?: string;
    gcia?: string;
    departamento?: string;
    contratista?: string;
}

export interface IPaciente
{    
    uid_paciente?: number;
    ci?: string;
    nombre?: string;
    apellido?: string;
    id_departamento?: number;
    es_contratista?: boolean;
    fechanac?: string;
    sexo?: string;
    cargo?: string;
    turno?: string;
    antiguedad_puesto?: string;
    fecha_ingreso?: string;
    tipo_sangre?: string;
    lugar_nac ?: string;
    edo_civil ?: string;
    nacionalidad?: string;
    telefono?: string;
    direccion_hab?: string;
    fecharegistro?: string;
    id_contratista?: number;
    mano_dominante?: string;
    frecuencia_rotacion?: string;
    nivel_educativo?: string;
    tipo_vivienda?: string;
    vivienda_propia?: string;
    medio_transp_trabajo?: string;
    alergia?: string;
    tipo_discapacidad?: string;
    desc_discapacidad?: string;
    estado_paciente?: string;    
}

export interface IPacienteConSupervisores{
    uid_paciente?: number;
    ci?: string;
    nombre?: string;
    apellido?: string;
    id_departamento?: number;
    es_contratista?: boolean;
    fechanac?: string;
    sexo?: string;
    cargo?: string;
    turno?: string;
    antiguedad_puesto?: string;
    fecha_ingreso?: string;
    tipo_sangre?: string;
    lugar_nac ?: string;
    edo_civil ?: string;
    nacionalidad?: string;
    telefono?: string;
    direccion_hab?: string;
    fecharegistro?: string;
    id_contratista?: number;
    mano_dominante?: string;
    frecuencia_rotacion?: string;
    nivel_educativo?: string;
    tipo_vivienda?: string;
    vivienda_propia?: string;
    medio_transp_trabajo?: string;
    alergia?: string;
    tipo_discapacidad?: string;
    desc_discapacidad?: string;
    estado_paciente?: string;
    edad?: any;
    nombre_completo?: string;
    gcia?: string;
    departamento?: string;
    contratista?: string;
    supervisor?: string; 
    nombres_jefe?: string;
}